apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app-1
  labels:
    app: app-1
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app-1
    spec:
      containers:
      - name: gunicorn-1
        image: vincentdesmet/flask_app:1.0
        volumeMounts:
        - name: images
          mountPath: /usr/src/app/config
        ports:
        - containerPort: 5000
          protocol: TCP
      restartPolicy: Always
      volumes:
      - name: images
        configMap:
          name: app-images
